version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: 'bank'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'bankuser'
    ports:
      - '5432:5432'

  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/bank'
      SPRING_DATASOURCE_USERNAME: 'bankuser'
      SPRING_DATASOURCE_PASSWORD: 'password'
    depends_on:
      - postgres
